# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/minimal_code_favicon_rounded.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
    since      = 2026
    customText = ""

[dateFormat]
    published   = ":date_full"
    lastUpdated = ":date_full"

[sidebar]
    emoji    = "🧑‍💻"
    subtitle = "Software Engineer | Tech Enthusiast"
    avatar   = "img/avatar.jpg"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
    enabled  = true
    provider = "waline"

    [comments.waline]
        serverURL    = "https://waline-backend-iota.vercel.app"
        lang         = "en"
        pageview     = ""
        emoji        = [
            "https://unpkg.com/@waline/emojis@1.0.1/tw-emoji",
            "https://unpkg.com/@waline/emojis@1.0.1/bilibili",
            "https://unpkg.com/@waline/emojis@1.0.1/qq",
            "https://unpkg.com/@waline/emojis@1.0.1/weibo",
            "https://unpkg.com/@waline/emojis@1.0.1/alus",
            "https://unpkg.com/@waline/emojis@1.0.1/tieba",
            "https://unpkg.com/@waline/emojis@1.0.1/tw-body",
            "https://unpkg.com/@waline/emojis@1.0.1/tw-food",
            "https://unpkg.com/@waline/emojis@1.0.1/tw-people",
            "https://unpkg.com/@waline/emojis@1.0.1/tw-sport",
            "https://unpkg.com/@waline/emojis@1.0.1/tw-object",
            "https://unpkg.com/@waline/emojis@1.0.1/tw-weather"
        ]
        requiredMeta = ["name", "email", "url"]

        [comments.waline.locale]
            admin       = "Admin"
            placeholder = ""
